### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#23]
Add/Edit/Delete

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
https://github.com/documoto/rocket/pull/1281

![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/05fb3150-5526-4a44-a607-74fa351dd79c)
