### ISSUE TITLE
News Item

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#26]
Add/Edit/Delete

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
news items tests added https://github.com/documoto/rocket/pull/1286
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/41a5d946-cff2-4a89-8bb4-d7639e812cf4)
