### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#29]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/ca585bce-8979-45d8-93f2-71c45f59a313)
Styles testing is currently implemented in the above described way.
Set primary color to default step is skipped as ember doesn't get loaded consistently for the second time during automation execution.

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1322
