### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#30]
Add/Edit/Delete

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
https://github.com/documoto/rocket/pull/1279
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/97082e2d-b934-44ad-844c-2b89a7839aaa)
