### ISSUE TITLE
Part List Columns

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#33]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1290

![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/8dabfa19-f1c5-460b-83b0-f825fb932f78)
