### ISSUE TITLE
Library Settings

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#34]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1329

**Comment by AlexKldnski** [comment]
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/9f8c7d8a-3aa2-4834-960c-daaf061972dd)
