### ISSUE TITLE
Browse Flows

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#35]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/5c28c0a2-ff01-40ed-b63b-6c3fc06b9849)
Tests are created / verified / merged
