### ISSUE TITLE
Storefront Settings

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#37]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by melissabruckner** [comment]
test/specs/rocket-admin/storefront/admin-store-front-settings.js

Still need to update a setting and verify

**Comment by AlexKldnski** [comment]
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/ebf9a881-9f2e-4d6c-878b-55021264521a)

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1319
