### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#44]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1338

**Comment by AlexKldnski** [comment]
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/5b255e67-8921-4173-a5c4-36df2b0bc2a1)
