### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#46]

**Comment by melissabruckner** [comment]
This one I was thinking we should extend ticket #49 to include the different types of user groups.  For example, log in as a tenant admin user and validate users only tenant admins should have are available and so on with Org, Publisher, Reports and Exporter.

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1340

**Comment by AlexKldnski** [comment]
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/0b391771-8d21-46f1-96a9-c4878bc52938)
