### ISSUE TITLE
Library Search

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#50]
Converting some of the search tests from cucumber/java to webdriver/node - ties to #45 - same code base.

**Comment by AlexKldnski** [comment]
The following Java+Cucumber test project is used to mirror its steps implementing "Library Search" testing in WdIO framework
https://github.com/documoto/rocketintegration/tree/master/src/test/resources/rocketLibrary/SearchFlows

**Comment by AlexKldnski** [comment]
"Breadcrumb" tests
PR: https://github.com/documoto/rocket/pull/1372

**Comment by AlexKldnski** [comment]
Multiple-search
PR: https://github.com/documoto/rocket/pull/1375

**Comment by AlexKldnski** [comment]
Search All
PR: https://github.com/documoto/rocket/pull/1376

**Comment by AlexKldnski** [comment]
"Search-types" and "search-view" tests
PR: https://github.com/documoto/rocket/pull/1383
