### ISSUE TITLE
Extend Print Settings to include part columns

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#58]
Related to https://github.com/documoto/enterprise/issues/1749

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1346

The code is added into "it creates print setting" block that adds an extra item into "Parts Pages" / "Part Columns" section list, then it saves changes, then it verifies part columns elements list length matches selected items list length in the "Add Categories" dropdown list, then it verifies elements names' values match each other in those lists.

Another "it" block - "edit a print setting" - has got a code that deletes the last item from "Parts Pages" / "Part Columns" section list, then it saves changes, then it verifies deleted item is not in the list anymore.
