### ISSUE TITLE
Supersede Part

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#6]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1298

![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/fed12524-316f-4fb3-bf08-2313d343077c)
