### ISSUE TITLE
Library - Page

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#68]
The following Java+Cucumber test project is used to mirror its steps implementing "Page" testing in WdIO framework
https://github.com/documoto/rocketintegration/tree/master/src/test/resources/rocketLibrary/PageFlows

**Comment by AlexKldnski** [comment]
Page-info test => PR: https://github.com/documoto/rocket/pull/1462

**Comment by AlexKldnski** [comment]
"bom-direction" and "part-name-link" tests => PR: https://github.com/documoto/rocket/pull/1489

**Comment by AlexKldnski** [comment]
"bom-icons" & bom-part-tags & "bom-pricing" tests => PR: https://github.com/documoto/rocket/pull/1507

**Comment by AlexKldnski** [comment]
The ticket is on hold due to current library bom architecture changes revert "Roll back Library BOM List/Viewer to version prior to #1826" #1936

**Comment by AlexKldnski** [comment]
"hotpoints" test => PR: https://github.com/documoto/rocket/pull/1545
