### ISSUE TITLE
Library - Part

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#69]
The following Java+Cucumber test project is used to mirror its steps implementing "Part" testing in WdIO framework
https://github.com/documoto/rocketintegration/tree/master/src/test/resources/rocketLibrary/PartFlows

**Comment by AlexKldnski** [comment]
Part-flows.js / User should see Part Info (all capabilities) test => PR: https://github.com/documoto/rocket/pull/1536

**Comment by AlexKldnski** [comment]
Part-flows test suite finalized in PR: https://github.com/documoto/rocket/pull/1538
