### ISSUE TITLE
Create Assembly

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#7]

**Comment by melissabruckner** [comment]
https://app.smartsheet.com/sheets/7Wcm9gjHV5C9v3vwvfwRp947QXFVQxrCF5Gw8JX1?view=grid

**Comment by AlexKldnski** [comment]
![image.png](https://images.zenhubusercontent.com/60b6c112944166daaf1067a4/a95dbfbc-4b1f-42ae-97af-ed3f5ffa2f1b)

**Comment by AlexKldnski** [comment]
PR: https://github.com/documoto/rocket/pull/1313
