### ISSUE TITLE
Library - Settings

### ISSUE THREAD

**Issue by melissabruckner** [documoto/testing#70]
The following Java+Cucumber test project is used to mirror its steps implementing "Settings" testing in WdIO framework
https://github.com/documoto/rocketintegration/tree/master/src/test/resources/rocketLibrary/SettingsFlows

**Comment by AlexKldnski** [comment]
It's necessary to extend an existing test suite so it should check locale updates both in Rocket Library and Admin

**Comment by AlexKldnski** [comment]
The code is partially commented in the test file "./test/specs/rocket-library/settings/preferences.js" due to an existing issue documoto/enterprise#1865.
Once the issue is resolved, the code need to be uncommented and verified working properly.
The follow-up ticket #78 is created.

**Comment by AlexKldnski** [comment]
https://github.com/documoto/rocket/pull/1529
